# Generated by Django 5.0.14 on 2025-10-19 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='MoveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(max_length=100)),
                ('from_building', models.CharField(blank=True, max_length=100, null=True)),
                ('from_address', models.CharField(blank=True, max_length=255, null=True)),
                ('to_city', models.CharField(max_length=100)),
                ('to_building', models.CharField(blank=True, max_length=100, null=True)),
                ('to_address', models.CharField(blank=True, max_length=255, null=True)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='app.item')),
                ('moved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moved_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
