# Generated by Django 5.0.14 on 2025-10-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_item_location_item_address_item_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='building',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='moverequest',
            name='from_address',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AlterField(
            model_name='moverequest',
            name='from_building',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='moverequest',
            name='from_city',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='moverequest',
            name='moved_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moverequest',
            name='to_address',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AlterField(
            model_name='moverequest',
            name='to_building',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='moverequest',
            name='to_city',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
