# Generated by Django 4.2.26 on 2025-11-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_citylocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citylocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='citylocation',
            name='longitude',
        ),
    ]
