# Generated by Django 4.2.26 on 2025-11-08 13:45

from django.db import migrations

def forwards(apps, schema_editor):
    City = apps.get_model("app", "City")
    Building = apps.get_model("app", "Building")
    Item = apps.get_model("app", "Item")

    cache_city = {}
    cache_build = {}

    qs = Item.objects.all().iterator(chunk_size=1000)
    for it in qs:
        city_name = (it.city or "").strip() or "Unknown"
        bld_name  = (it.building or "").strip() or "Default"


        key_city = city_name.lower()
        city = cache_city.get(key_city)
        if not city:
            city, _ = City.objects.get_or_create(name=city_name)
            cache_city[key_city] = city

        key_build = (city.id, bld_name.lower())
        bld = cache_build.get(key_build)
        if not bld:
            bld, _ = Building.objects.get_or_create(
                city=city,
                name=bld_name,
                defaults=dict(
                    address=it.address or "",
                    lat=it.lat,
                    lng=it.lng,
                ),
            )
            cache_build[key_build] = bld

        if it.building_ref_id != bld.id:
            it.building_ref_id = bld.id
            it.save(update_fields=["building_ref"])

def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_city_building_item_building_ref'),
    ]

    operations = [
    ]




