# Generated by Django 5.2.8 on 2025-11-09 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_backfill_building_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('from_city', models.CharField(max_length=100)),
                ('from_building', models.CharField(max_length=100)),
                ('from_address', models.CharField(max_length=255)),
                ('to_city', models.CharField(blank=True, default='', max_length=100)),
                ('to_building', models.CharField(blank=True, default='', max_length=100)),
                ('to_address', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='app.item')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
