# Generated by Django 5.0.14 on 2025-11-10 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_threshold', models.IntegerField(default=10, help_text='Alert when stock falls below this number')),
                ('critical_stock_threshold', models.IntegerField(default=5, help_text='Critical alert threshold')),
                ('enable_low_stock_alerts', models.BooleanField(default=True)),
                ('enable_delivery_alerts', models.BooleanField(default=True)),
                ('enable_move_alerts', models.BooleanField(default=True)),
                ('auto_mark_read', models.BooleanField(default=False, help_text='Automatically mark as read when viewing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('low_stock', 'Low Stock Alert'), ('delivery_update', 'Delivery Update'), ('item_moved', 'Item Moved'), ('delivery_created', 'Delivery Created'), ('delivery_finished', 'Delivery Finished'), ('delivery_cancelled', 'Delivery Cancelled')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.delivery')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='app_notific_user_id_3dfd65_idx'), models.Index(fields=['user', '-created_at'], name='app_notific_user_id_1ee635_idx')],
            },
        ),
    ]
